/*
 * This file is part of Safester.                                    
 * Copyright (C) 2019, KawanSoft SAS
 * (https://www.Safester.net). All rights reserved.                                
 *                                                                               
 * Safester is free software; you can redistribute it and/or                 
 * modify it under the terms of the GNU Lesser General Public                    
 * License as published by the Free Software Foundation; either                  
 * version 2.1 of the License, or (at your option) any later version.            
 *                                                                               
 * Safester is distributed in the hope that it will be useful,               
 * but WITHOUT ANY WARRANTY; without even the implied warranty of                
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU             
 * Lesser General Public License for more details.                               
 *                                                                               
 * You should have received a copy of the GNU Lesser General Public              
 * License along with this library; if not, write to the Free Software           
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  
 * 02110-1301  USA
 * 
 * Any modifications to this file must keep this entire header
 * intact.
 */
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Safester {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Safester.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        internal static string Rememberme {
            get {
                return ResourceManager.GetString("Rememberme", resourceCulture);
            }
        }
        
        internal static string Pleasewait {
            get {
                return ResourceManager.GetString("Pleasewait", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        internal static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        internal static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        internal static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        internal static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string NewMail {
            get {
                return ResourceManager.GetString("NewMail", resourceCulture);
            }
        }
        
        internal static string ErrorInputUserName {
            get {
                return ResourceManager.GetString("ErrorInputUserName", resourceCulture);
            }
        }
        
        internal static string ErrorInputUserPassPhrase {
            get {
                return ResourceManager.GetString("ErrorInputUserPassPhrase", resourceCulture);
            }
        }
        
        internal static string ErrorInputUserPassPhrase1 {
            get {
                return ResourceManager.GetString("ErrorInputUserPassPhrase1", resourceCulture);
            }
        }
        
        internal static string ErrorInputUserPassPhrase2 {
            get {
                return ResourceManager.GetString("ErrorInputUserPassPhrase2", resourceCulture);
            }
        }
        
        internal static string ErrorInputUserEmail {
            get {
                return ResourceManager.GetString("ErrorInputUserEmail", resourceCulture);
            }
        }
        
        internal static string ErrorInputUserEmail1 {
            get {
                return ResourceManager.GetString("ErrorInputUserEmail1", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string SentFromAndroid {
            get {
                return ResourceManager.GetString("SentFromAndroid", resourceCulture);
            }
        }
        
        internal static string SentFromiOS {
            get {
                return ResourceManager.GetString("SentFromiOS", resourceCulture);
            }
        }
        
        internal static string CANNOT_CONNECT_SERVER {
            get {
                return ResourceManager.GetString("CANNOT_CONNECT_SERVER", resourceCulture);
            }
        }
        
        internal static string ALERT_CONFIRM_EMAIL {
            get {
                return ResourceManager.GetString("ALERT_CONFIRM_EMAIL", resourceCulture);
            }
        }
        
        internal static string ALERT_ACCOUNT_EXIST {
            get {
                return ResourceManager.GetString("ALERT_ACCOUNT_EXIST", resourceCulture);
            }
        }
        
        internal static string ALERT_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("ALERT_EMAIL_INVALID", resourceCulture);
            }
        }
        
        internal static string ALERT_REGISTER_SUCCESS {
            get {
                return ResourceManager.GetString("ALERT_REGISTER_SUCCESS", resourceCulture);
            }
        }
        
        internal static string ALERT_COUPON_INVALID {
            get {
                return ResourceManager.GetString("ALERT_COUPON_INVALID", resourceCulture);
            }
        }
        
        internal static string ALERT_NOEMAILAPP {
            get {
                return ResourceManager.GetString("ALERT_NOEMAILAPP", resourceCulture);
            }
        }
        
        internal static string ALERT_NODEFAULTAPP {
            get {
                return ResourceManager.GetString("ALERT_NODEFAULTAPP", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        internal static string SupportReportBug {
            get {
                return ResourceManager.GetString("SupportReportBug", resourceCulture);
            }
        }
        
        internal static string Compose {
            get {
                return ResourceManager.GetString("Compose", resourceCulture);
            }
        }
        
        internal static string MailFrom {
            get {
                return ResourceManager.GetString("MailFrom", resourceCulture);
            }
        }
        
        internal static string MailTo {
            get {
                return ResourceManager.GetString("MailTo", resourceCulture);
            }
        }
        
        internal static string MailCc {
            get {
                return ResourceManager.GetString("MailCc", resourceCulture);
            }
        }
        
        internal static string MailBcc {
            get {
                return ResourceManager.GetString("MailBcc", resourceCulture);
            }
        }
        
        internal static string MailSubject {
            get {
                return ResourceManager.GetString("MailSubject", resourceCulture);
            }
        }
        
        internal static string MailDate {
            get {
                return ResourceManager.GetString("MailDate", resourceCulture);
            }
        }
        
        internal static string MailDisplayMsgAsStored {
            get {
                return ResourceManager.GetString("MailDisplayMsgAsStored", resourceCulture);
            }
        }
        
        internal static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        internal static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        internal static string ClipboardSuccess {
            get {
                return ResourceManager.GetString("ClipboardSuccess", resourceCulture);
            }
        }
        
        internal static string FileDownloadFailure {
            get {
                return ResourceManager.GetString("FileDownloadFailure", resourceCulture);
            }
        }
        
        internal static string FileDownloadToFolderAndroid {
            get {
                return ResourceManager.GetString("FileDownloadToFolderAndroid", resourceCulture);
            }
        }
        
        internal static string FileDownloadToFolderiOS {
            get {
                return ResourceManager.GetString("FileDownloadToFolderiOS", resourceCulture);
            }
        }
        
        internal static string DeleteMail {
            get {
                return ResourceManager.GetString("DeleteMail", resourceCulture);
            }
        }
        
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        internal static string AvailableSoon {
            get {
                return ResourceManager.GetString("AvailableSoon", resourceCulture);
            }
        }
        
        internal static string ChangePass {
            get {
                return ResourceManager.GetString("ChangePass", resourceCulture);
            }
        }
        
        internal static string ChangePassHint {
            get {
                return ResourceManager.GetString("ChangePassHint", resourceCulture);
            }
        }
        
        internal static string ConfirmLogout {
            get {
                return ResourceManager.GetString("ConfirmLogout", resourceCulture);
            }
        }
        
        internal static string ImportContacts {
            get {
                return ResourceManager.GetString("ImportContacts", resourceCulture);
            }
        }
        
        internal static string ImportContactsHint {
            get {
                return ResourceManager.GetString("ImportContactsHint", resourceCulture);
            }
        }
        
        internal static string ImportContactsSuccess {
            get {
                return ResourceManager.GetString("ImportContactsSuccess", resourceCulture);
            }
        }
        
        internal static string SaveAsDraft {
            get {
                return ResourceManager.GetString("SaveAsDraft", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string TypeText {
            get {
                return ResourceManager.GetString("TypeText", resourceCulture);
            }
        }
        
        internal static string RemoveAttachment {
            get {
                return ResourceManager.GetString("RemoveAttachment", resourceCulture);
            }
        }
        
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        internal static string InputReceiverEmail {
            get {
                return ResourceManager.GetString("InputReceiverEmail", resourceCulture);
            }
        }
        
        internal static string InputSubject {
            get {
                return ResourceManager.GetString("InputSubject", resourceCulture);
            }
        }
        
        internal static string FileAdded {
            get {
                return ResourceManager.GetString("FileAdded", resourceCulture);
            }
        }
        
        internal static string MessageEncrypted {
            get {
                return ResourceManager.GetString("MessageEncrypted", resourceCulture);
            }
        }
        
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        internal static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        internal static string RegisterUserHint {
            get {
                return ResourceManager.GetString("RegisterUserHint", resourceCulture);
            }
        }
        
        internal static string RegisterUserHint1 {
            get {
                return ResourceManager.GetString("RegisterUserHint1", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string Passphrase {
            get {
                return ResourceManager.GetString("Passphrase", resourceCulture);
            }
        }
        
        internal static string ConfirmPassphrase {
            get {
                return ResourceManager.GetString("ConfirmPassphrase", resourceCulture);
            }
        }
        
        internal static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        internal static string CryptographySettings {
            get {
                return ResourceManager.GetString("CryptographySettings", resourceCulture);
            }
        }
        
        internal static string MailboxSize {
            get {
                return ResourceManager.GetString("MailboxSize", resourceCulture);
            }
        }
        
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        internal static string AllowNotification {
            get {
                return ResourceManager.GetString("AllowNotification", resourceCulture);
            }
        }
        
        internal static string MessagePerScroll {
            get {
                return ResourceManager.GetString("MessagePerScroll", resourceCulture);
            }
        }
        
        internal static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        internal static string AddSignatureHint {
            get {
                return ResourceManager.GetString("AddSignatureHint", resourceCulture);
            }
        }
        
        internal static string AddSignature {
            get {
                return ResourceManager.GetString("AddSignature", resourceCulture);
            }
        }
        
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        internal static string TakePhoto {
            get {
                return ResourceManager.GetString("TakePhoto", resourceCulture);
            }
        }
        
        internal static string SelectPhoto {
            get {
                return ResourceManager.GetString("SelectPhoto", resourceCulture);
            }
        }
        
        internal static string PickFile {
            get {
                return ResourceManager.GetString("PickFile", resourceCulture);
            }
        }
    }
}
